### ISSUE TITLE
SummarizedExperiment for user-facing functions 

### ISSUE THREAD

**Issue by esebesty** [SU-CompBio/SplicingFactory#5]
Ideally, `calculate_diversity` (and `calculate_method`) should return a `SummarizedExperiment`, that is the input for `calculate_difference`. This way, we can store gene/transcript annotation in a `DataFrame` accessible  using the function `rowData()`, instead of additional columns in the `data.frame` that contains the expression/diversity values.

Besides `SummarizedExperiment`, should `calculate_difference` also accept a `matrix` and `data.frame` as input or do we ask users to create a `SummarizedExperiment` object?

`calculate_difference` should return a `data.frame`, not a `SummarizedExperiment` object.

**Comment by LiNk-NY** [comment]
Hi Endre @esebesty 
IMO, yes, you can also accept a `matrix` and `data.frame` input **and** it would be nice to have a uniform and expected `SummarizedExperiment` output. Note that SE is a standard adapter to other packages / functions in the Bioconductor ecosystem. 
Thanks. 
-Marcel

**Comment by esebesty** [comment]
OK, working on it. We will support a SummarizedExperiment input and output. `SummarizedExperiment` output for `calculate_diversity` is fine, but what would be the structure for a `SummarizedExperiment` output of `calculate_difference`? Here we don't have sample level results anymore, but log fold-changes, p-values, etc.
