### ISSUE TITLE
Use more recent example dataset

### ISSUE THREAD

**Issue by esebesty** [SU-CompBio/SplicingFactory#6]
Use data from `curatedTCGAData` or `GenomicDataCommons` for the vignette and example dataset, instead of the legacy TCGA data.

**Comment by esebesty** [comment]
Or use `RTCGAToolbox` and `TCGAbiolinks`.

**Comment by esebesty** [comment]
Hi  Marcel @LiNK-NY 

Based on your suggestions [here](https://github.com/Bioconductor/Contributions/issues/1517), we checked a number of datasets and download options. However, both the `curatedTCGAData`,  the `GenomicDataCommons` and the `RTCGAToolbox` seem to contain gene-level data only. They might be RSEM results, but seem to be summarized at the gene level. We might have missed some function or parameter, let me know if this is the case.

We can download some transcript level data using `TCGAbiolinks` but this is legacy data, there is no transcript level data in the non-legacy data. However, the download takes a significant amount of time and the tsv file for a single sample is ~2.4 Mb. That's why we included an example dataset in the package, that is actually coming from the `TCGAbiolinks` legacy data, so it is not too large and the vignette can be generated in a reasonable amount of time.

If you have no other suggestions, we can either:

- add a more detailed description in the vignette, [around this section](https://github.com/SU-CompBio/SplicingFactory/blob/master/vignettes/SplicingFactory.Rmd#L96), so the source of the data is explained in detail
- add the detailed description [here](https://github.com/SU-CompBio/SplicingFactory/blob/master/R/tcga_brca_luma_dataset.R)

and we still use the data included in the package.

OR, a last resort would be to use some non-TCGA dataset where we have transcript level read counts, or TPM values available in an R data package.

What do you think?

**Comment by LiNk-NY** [comment]
Hi Endre @esebesty 

Yes, they provide gene level data. It may be better to provide your own dataset then. 
It would be helpful for users to be able to see how the dataset was generated for the
package, if possible. 
To this end, you can provide an R script in `inst/scripts` or `data-raw` folder that shows
how you processed the data unless it was provided as-is by a publication. For the latter,
you can add a note in the data description. 
Thanks!
